project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  navbar:
    logo: deepart.png
    left: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



