project:
  type: website
  output-dir: docs

website:
  title: "Yao Hao's Personal Website"
  navbar:
    logo: images/mepic.jfif
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      - titanic_txt.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



