---
title: "Yao Hao's Personal Website"
---

I am currently a Applied Computing undergraduate with a specialisation in Fintech at the Singapore Institute of Technology, I have developed a passion for leveraging technology to drive innovation in the financial sector. My journey began during my polytechnic years, and I had the privilege of implementing classroom knowledge into real-world impact during my internship at The FinLab. It was a transformative experience witnessing how technology can enhance efficiency and bring benefits to the industry.

My academic journey equipped me with a diverse skill set such as Python, C, C#, SQL, and RPA, enabling me to navigate the dynamic landscape of fintech. My academic foundation, coupled with practical experience, positions me to contribute meaningfully to the intersection of finance and technology.

During my free time, I spend valuable moments with family and friends through games and outdoor activities like playing basketball, hiking and running. These experiences not only create lasting memories but also strengthen bonds with loved ones, ensuring no regrets.

I like to go travelling as well, click here to go to my travel blog.

My LinkedIn Profile <https://www.linkedin.com/in/koh-yao-hao/>.

```{r}
1 + 1
```
